# Top-level configuration
name = "di-dev"
main = "src/index.ts"

compatibility_flags = [ "formdata_parser_supports_files" ]
compatibility_date = "2022-10-12"

kv_namespaces = [
  { binding = "INQUIRIES", id = "KV_ID", preview_id = "KV_ID" },
]

[[r2_buckets]]
binding = 'R2_INQUIRIES'
bucket_name = 'R2_INQUIRIES'
preview_bucket_name = 'R2_INQUIRIES'

[env.prod]
name = "di-prod"
kv_namespaces = [
  { binding = "INQUIRIES", id = "<KV_ID>"},
]